<a href="https://colab.research.google.com/github/PisutSukpool/BADS/blob/main/Classification%20and%20Clustering/Wine_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
df_wine = X.merge(y, left_index=True, right_index=True)
df_wine

     Alchol  Malic_Acid   Ash  ...  OD280  Proline  Cultivator
0     14.23        1.71  2.43  ...   3.92   1065.0           0
1     13.20        1.78  2.14  ...   3.40   1050.0           0
2     13.16        2.36  2.67  ...   3.17   1185.0           0
3     14.37        1.95  2.50  ...   3.45   1480.0           0
4     13.24        2.59  2.87  ...   2.93    735.0           0
..      ...         ...   ...  ...    ...      ...         ...
173   13.71        5.65  2.45  ...   1.74    740.0           2
174   13.40        3.91  2.48  ...   1.56    750.0           2
175   13.27        4.28  2.26  ...   1.56    835.0           2
176   13.17        2.59  2.37  ...   1.62    840.0           2
177   14.13        4.10  2.74  ...   1.60    560.0           2

[178 rows x 14 columns]